version: 2.1
executors:
  ci-executor:
    docker:
      - image: githubtraining/ci-custom:latest
jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
<<<<<<< HEAD

=======
>>>>>>> 0973e63ea7b9581cc1fb338f8b6ea3f266963935
